### 201 - CREATE NEW USER WITH DEFAULT ROLES
POST http://localhost:8088/app/api/v3/users
Content-Type: application/json

{
  "username": "m1",
  "password": "1qaZXsw2",
  "confirmPassword": "1qaZXsw2"
}
### 400 - VALID ERROR: USERNAME IS ABOVE MIN LENGTH
POST http://localhost:8088/app/api/v3/users
Content-Type: application/json

{
  "username": "m",
  "password": "1qaZXsw2",
  "confirmPassword": "1qaZXsw2"
}
### 201 - CREATE USER WITH ALLOWED ROLE
POST http://localhost:8088/app/api/v3/users
Content-Type: application/json

{
  "username": "m2",
  "password": "1qaZXsw2",
  "confirmPassword": "1qaZXsw2",
  "roles": [
    "STUDENT"
  ]
}
### 400 - VALID ERROR: ADMIN ROLE IS NOT ALLOWED
POST http://localhost:8088/app/api/v3/users
Content-Type: application/json

{
  "username": "m3",
  "password": "1qaZXsw2",
  "confirmPassword": "1qaZXsw2",
  "roles": [
    "ADMIN"
  ]
}
### 400 - VALID ERROR: ADMIN ROLE IS NOT ALLOWED
POST http://localhost:8088/app/api/v3/users
Content-Type: application/json

{
  "username": "m4",
  "password": "1qaZXsw2",
  "confirmPassword": "1qaZXsw2",
  "roles": [
    "RANDOM_ROLE"
  ]
}