spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quizer
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    parameters:
      data-file-prefix: dev
server:
  port: 8088