version: '3.1'

services:
  postgres:
    container_name: quizer-db
    image: postgres:14.3
    restart: "unless-stopped"
    environment:
      - POSTGRES_DB=quizer
      - POSTGRES_USER=quizer
      - POSTGRES_PASSWORD=quizer
    ports:
        - "5430:5432"
  prometheus:
    image: prom/prometheus:v2.26.1
    network_mode: host
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
  grafana:
    network_mode: host
    image: grafana/grafana:7.5.6
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data:
