version: '3'
services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: quizer
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  mongo:
    image: mongo:5.0.19
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: quizer
      MONGO_INITDB_ROOT_PASSWORD: quizer
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://quizer:quizer@mongo:27017/
volumes:
  db_data:
  mongo_data: